import React, { useState, useEffect, useRef, useCallback } from "react";
import {
  UploadCloud,
  X,
  CheckCircle,
  Tag,
  ImagePlus,
  Film,
  Info,
  Loader2,
  AlertCircle,
  ChevronRight,
  ChevronLeft,
  Settings,
  Eye,
  Type,
  Volume2,
  VolumeX,
  FileVideo,
  Clock,
  Zap,
  Globe,
  Lock,
  EyeOff,
  Sparkles,
  Video,
  Play,
  Pause,
  RotateCcw,
  Save,
  Trash2
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { getAuth } from "firebase/auth";
import { API_URL } from "../utils/constants";
import { useNotifications } from "../context/NotificationContext";

/**
 * Premium UploadModal
 * A high-end video upload experience with frame extraction, 
 * drag-and-drop, and real-time metadata processing.
 */

interface UploadModalProps {
  onClose: () => void;
  onUploaded?: () => void;
}

export default function UploadModal({ onClose, onUploaded }: UploadModalProps) {
  const { addNotification, startVideoReadyPolling } = useNotifications();
  const [step, setStep] = useState(1);
  const [isDragging, setIsDragging] = useState(false);
  const [isMuted, setIsMuted] = useState(true);
  const [isPlaying, setIsPlaying] = useState(false);

  // File States
  const [file, setFile] = useState(null);
  const [thumbnail, setThumbnail] = useState(null);
  const [thumbnailPreview, setThumbnailPreview] = useState("");
  const [autoGeneratedThumbs, setAutoGeneratedThumbs] = useState([]);
  const [videoMetadata, setVideoMetadata] = useState(null);

  // Metadata States
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [visibility, setVisibility] = useState("Public");
  const [tags, setTags] = useState("");
  const [category, setCategory] = useState("Entertainment");

  // AI/Enhancement States
  const [suggestedTags, setSuggestedTags] = useState([]);
  const [titleSuggestions, setTitleSuggestions] = useState([]);
  const [generatingAI, setGeneratingAI] = useState(false);

  // Status States
  const [uploading, setUploading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [uploadSpeed, setUploadSpeed] = useState(0);
  const [timeRemaining, setTimeRemaining] = useState(0);
  const [error, setError] = useState("");
  const [videoPreview, setVideoPreview] = useState("");
  const [processingStage, setProcessingStage] = useState("");

  const xhrRef = useRef(null);
  const fileInputRef = useRef(null);
  const thumbnailInputRef = useRef(null);
  const previewVideoRef = useRef(null);
  const uploadStartTime = useRef(null);
  const lastLoaded = useRef(0);

  /* ----------------------------------
      Enhanced Frame Extraction
  ---------------------------------- */
  const extractFrames = useCallback((videoFile) => {
    const video = document.createElement("video");
    const canvas = document.createElement("canvas");
    const context = canvas.getContext("2d");
    const frames = [];
    const url = URL.createObjectURL(videoFile);

    video.src = url;
    video.preload = "metadata";

    video.onloadedmetadata = () => {
      const duration = video.duration;
      canvas.width = video.videoWidth / 3;
      canvas.height = video.videoHeight / 3;

      // Store video metadata
      setVideoMetadata({
        duration: Math.round(duration),
        width: video.videoWidth,
        height: video.videoHeight,
        size: videoFile.size,
        type: videoFile.type,
        name: videoFile.name
      });

      // Sequential capture — Promise.all fires all seeks simultaneously which causes:
      // 1) video.onseeked is a property assignment so each iteration overwrites the
      //    previous; only the last handler survives, 5 of 6 promises never resolve.
      // 2) All draws read the same shared canvas at whatever frame settled last.
      // Fix: await each seek one at a time with addEventListener + { once: true }.
      const captureSequential = async (times: number[]) => {
        for (const time of times) {
          await new Promise<void>((resolve) => {
            video.addEventListener("seeked", () => {
              context.drawImage(video, 0, 0, canvas.width, canvas.height);
              frames.push(canvas.toDataURL("image/jpeg", 0.8));
              resolve();
            }, { once: true });
            video.currentTime = time;
          });
        }
      };

      // Extract 6 thumbnails at different timestamps
      const times = [
        duration * 0.1,
        duration * 0.25,
        duration * 0.4,
        duration * 0.5,
        duration * 0.6,
        duration * 0.75
      ];

      captureSequential(times)
        .then(() => {
          setAutoGeneratedThumbs(frames);
          // Auto-select middle frame
          setThumbnailPreview(frames[3]);
          URL.revokeObjectURL(url);
        })
        .catch(err => {
          console.error("Frame extraction error:", err);
          URL.revokeObjectURL(url);
        });
    };

    video.onerror = () => {
      setError("Failed to load video. Please try a different file.");
      URL.revokeObjectURL(url);
    };
  }, []);

  /* ----------------------------------
      AI-Powered Suggestions
  ---------------------------------- */
  const generateAISuggestions = useCallback(() => {
    if (!title && !file) return;

    setGeneratingAI(true);

    // Simulate AI generation (replace with actual API call)
    setTimeout(() => {
      const baseName = file?.name.replace(/\.[^/.]+$/, "") || title;

      // Title suggestions
      setTitleSuggestions([
        `${baseName} - Full Video`,
        `${baseName} | ${category} Content`,
        `Amazing ${baseName} Experience`
      ]);

      // Tag suggestions based on category
      const tagMap = {
        Entertainment: ["entertainment", "fun", "viral", "trending"],
        Gaming: ["gaming", "gameplay", "lets play", "walkthrough"],
        Music: ["music", "audio", "song", "cover"],
        Education: ["educational", "tutorial", "learning", "howto"],
        Tech: ["technology", "review", "tech", "gadgets"]
      };

      setSuggestedTags(tagMap[category] || []);
      setGeneratingAI(false);
    }, 1500);
  }, [title, file, category]);

  /* ----------------------------------
      Lifecycle & Accessibility
  ---------------------------------- */
  useEffect(() => {
    const handleKeydown = (e) => {
      if (e.key === "Escape" && !uploading) {
        handleClose();
      }
    };
    window.addEventListener("keydown", handleKeydown);

    // Load draft from localStorage — only restore title if no file is loaded yet
    const draft = localStorage.getItem("airstream_draft");
    if (draft) {
      try {
        const d = JSON.parse(draft);
        // Only restore title from draft if user hasn't selected a file yet
        // AND draft title matches current file name (prevents stale title from prev session)
        if (!file) setTitle(d.title || "");
        // If file already selected, never overwrite with draft title
        setDescription(d.description || "");
        setTags(d.tags || "");
        setCategory(d.category || "Entertainment");
        setVisibility(d.visibility || "Public");
      } catch (e) {
        console.error("Draft parse error", e);
      }
    }

    return () => {
      window.removeEventListener("keydown", handleKeydown);
      if (videoPreview) URL.revokeObjectURL(videoPreview);
      if (thumbnailPreview && !thumbnailPreview.startsWith('data:')) {
        URL.revokeObjectURL(thumbnailPreview);
      }
    };
  }, [uploading]);

  // Auto-save draft
  useEffect(() => {
    if (title || description || tags) {
      const draftData = { title, description, tags, category, visibility };
      localStorage.setItem("airstream_draft", JSON.stringify(draftData));
    }
  }, [title, description, tags, category, visibility]);

  /* ----------------------------------
      Event Handlers
  ---------------------------------- */
  const processFile = (selected) => {
    if (!selected) return;

    if (!selected.type.startsWith("video/")) {
      setError("Please select a valid video file (MP4, MOV, AVI, etc.)");
      return;
    }

    const maxSize = 100 * 1024 * 1024;
    if (selected.size > maxSize) {
      setError(`File too large. Maximum size is 100MB.`);
      return;
    }

    setError("");
    setFile(selected);
    const url = URL.createObjectURL(selected);
    setVideoPreview(url);
    extractFrames(selected);

    // Clear stale draft title when new file is selected
    // Auto-fill title from filename — clean up garbage from filename
    const baseName = selected.name
      .replace(/\.[^/.]+$/, "")                                          // remove extension
      .replace(/\b(4K|2K|1080p|720p|480p|360p|144p|HDR|SDR|HEVC|x264|x265|BluRay|WEBRip|WEB-DL|BRRip|DVDRip|HDTV|UltraHD|Ultra HD|HQ|HD)\b/gi, "") // remove quality tags
      .replace(/\(HDYaar9\)|\[HDYaar9\]/gi, "")                        // remove site watermarks
      .replace(/\([^)]*\)|\[[^\]]*\]/g, "")                           // remove all (xxx) and [xxx]
      .replace(/[-_.]+/g, " ")                                            // dashes/underscores → spaces
      .replace(/\s{2,}/g, " ")                                           // collapse multiple spaces
      .trim();

    // Always replace title with new file's cleaned name
    // User can edit it manually after — but new file = new title
    setTitle(baseName.substring(0, 100));
  };

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setIsDragging(true);
    } else if (e.type === "dragleave") {
      setIsDragging(false);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);

    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleThumbnailChange = (e) => {
    const selected = e.target.files?.[0];
    if (!selected) return;

    if (!selected.type.startsWith("image/")) {
      setError("Please select a valid image file.");
      return;
    }

    setThumbnail(selected);
    const url = URL.createObjectURL(selected);
    setThumbnailPreview(url);
  };

  const handleClose = () => {
    if (uploading) {
      if (!confirm("Upload in progress. Are you sure you want to cancel?")) {
        return;
      }
      xhrRef.current?.abort();
    }
    onClose();
  };

  const addSuggestedTag = (tag) => {
    const currentTags = tags.split(',').map(t => t.trim()).filter(Boolean);
    if (!currentTags.includes(tag)) {
      setTags([...currentTags, tag].join(', '));
    }
  };

  const clearDraft = () => {
    localStorage.removeItem("airstream_draft");
    setTitle("");
    setDescription("");
    setTags("");
    setCategory("Entertainment");
    setVisibility("Public");
  };

  const formatBytes = (bytes) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  };

  const formatDuration = (seconds) => {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    if (h > 0) return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
    return `${m}:${s.toString().padStart(2, '0')}`;
  };

  const startUpload = async () => {
    if (!file) return setError("Please select a video file.");
    if (!title.trim()) return setError("Please add a title for your video.");

    setUploading(true);
    setError("");
    uploadStartTime.current = Date.now();
    lastLoaded.current = 0;

    try {
      const auth = getAuth();
      const user = auth.currentUser;

      if (!user) {
        setError("Please login first to upload.");
        setUploading(false);
        return;
      }

      const token = await user.getIdToken();

      const formData = new FormData();
      // Backend uses upload.single("file") — field name must be exactly "file"
      formData.append("file", file, file.name);

      // Send thumbnail as base64 text field — avoids MulterError since
      // upload.single("file") only accepts one file field.
      // The backend route will read req.body.thumbnail_base64 and save it.
      // Build thumbnail: resize to max 1280×720, compress to JPEG quality 0.85
      // This keeps the base64 string under 150KB — safe for multer fieldSize
      const buildThumbBase64 = async (): Promise<string | null> => {
        // Priority 1: user uploaded a custom image File — read it directly via
        // FileReader so we never depend on a blob: URL that may have been revoked.
        if (thumbnail) {
          try {
            const dataUrl = await new Promise<string>((resolve, reject) => {
              const reader = new FileReader();
              reader.onload = () => resolve(reader.result as string);
              reader.onerror = reject;
              reader.readAsDataURL(thumbnail);
            });

            // Resize to max 1280×720 before sending
            const img = await new Promise<HTMLImageElement>((resolve, reject) => {
              const i = new Image();
              i.onload = () => resolve(i);
              i.onerror = reject;
              i.src = dataUrl;
            });

            const MAX_W = 1280, MAX_H = 720;
            let w = img.naturalWidth || img.width;
            let h = img.naturalHeight || img.height;
            if (w > MAX_W || h > MAX_H) {
              const ratio = Math.min(MAX_W / w, MAX_H / h);
              w = Math.round(w * ratio);
              h = Math.round(h * ratio);
            }

            const canvas = document.createElement("canvas");
            canvas.width = w;
            canvas.height = h;
            const ctx = canvas.getContext("2d")!;
            ctx.drawImage(img, 0, 0, w, h);
            return canvas.toDataURL("image/jpeg", 0.85);
          } catch (e) {
            console.warn("[Upload] Custom thumbnail resize failed:", e);
            return null;
          }
        }

        // Priority 2: auto-generated frame (already a data: URL — safe to use directly)
        if (thumbnailPreview && thumbnailPreview.startsWith("data:")) {
          return thumbnailPreview;
        }

        // Priority 3: blob: URL fallback (less reliable, kept for edge cases)
        if (thumbnailPreview) {
          try {
            const img = await new Promise<HTMLImageElement>((resolve, reject) => {
              const i = new Image();
              i.onload = () => resolve(i);
              i.onerror = reject;
              i.src = thumbnailPreview;
            });

            const MAX_W = 1280, MAX_H = 720;
            let w = img.naturalWidth || img.width;
            let h = img.naturalHeight || img.height;
            if (w > MAX_W || h > MAX_H) {
              const ratio = Math.min(MAX_W / w, MAX_H / h);
              w = Math.round(w * ratio);
              h = Math.round(h * ratio);
            }

            const canvas = document.createElement("canvas");
            canvas.width = w;
            canvas.height = h;
            const ctx = canvas.getContext("2d")!;
            ctx.drawImage(img, 0, 0, w, h);
            return canvas.toDataURL("image/jpeg", 0.85);
          } catch (e) {
            console.warn("[Upload] Blob thumbnail resize failed:", e);
            return null;
          }
        }

        return null;
      };
      const thumbBase64 = await buildThumbBase64();
      if (thumbBase64) {
        // Hard cap: skip thumbnail if it exceeds 4MB (leave 1MB headroom under fieldSize)
        const MAX_THUMB_BYTES = 4 * 1024 * 1024;
        if (thumbBase64.length <= MAX_THUMB_BYTES) {
          formData.append("thumbnail_base64", thumbBase64);
          console.log(`[Upload] Thumbnail base64 size: ${Math.round(thumbBase64.length / 1024)}KB`);
        } else {
          console.warn(`[Upload] Thumbnail skipped — too large (${Math.round(thumbBase64.length / 1024)}KB)`);
        }
      }

      formData.append("title", title.trim());
      formData.append("description", description.trim());
      formData.append("visibility", visibility.toLowerCase());
      formData.append("tags", tags);
      formData.append("category", category);

      const xhr = new XMLHttpRequest();
      xhrRef.current = xhr;

      xhr.open("POST", `${API_URL}/upload`, true);
      xhr.setRequestHeader("Authorization", `Bearer ${token}`);

      let lastTime = Date.now();
      let lastLoadedBytes = 0;

      xhr.upload.onprogress = (e) => {
        if (e.lengthComputable) {
          const currentProgress = Math.round((e.loaded / e.total) * 100);
          setProgress(currentProgress);

          // Calculate upload speed
          const now = Date.now();
          const timeDiff = (now - lastTime) / 1000; // seconds
          const bytesDiff = e.loaded - lastLoadedBytes;

          if (timeDiff > 0.5) { // Update every 500ms
            const speed = bytesDiff / timeDiff; // bytes per second
            setUploadSpeed(speed);

            // Calculate time remaining
            const bytesRemaining = e.total - e.loaded;
            const secondsRemaining = bytesRemaining / speed;
            setTimeRemaining(Math.round(secondsRemaining));

            lastTime = now;
            lastLoadedBytes = e.loaded;
          }

          // Update processing stage
          if (currentProgress < 30) {
            setProcessingStage("Uploading video...");
          } else if (currentProgress < 60) {
            setProcessingStage("Processing metadata...");
          } else if (currentProgress < 90) {
            setProcessingStage("Generating thumbnails...");
          } else {
            setProcessingStage("Finalizing...");
          }
        }
      };

      xhr.onload = () => {
        if (xhr.status >= 200 && xhr.status < 300) {
          setStep(3);
          localStorage.removeItem("airstream_draft");

          // Parse video ID from upload response
          let videoId: string | null = null;
          try {
            const data = JSON.parse(xhr.responseText);
            videoId = String(data?.video?.id ?? data?.id ?? "");
          } catch { /* ignore parse errors */ }

          // 🔔 "Uploaded — now processing" notification
          addNotification({
            type: "info",
            title: "⏳ Video uploaded — processing started",
            message: `"${title || file?.name || "Your video"}" is being transcoded. We'll notify you when it's live.`,
          });

          // 🔁 Start polling for ready status — fires "live!" notification automatically
          if (videoId) {
            startVideoReadyPolling(videoId, title || file?.name || "Your video");
          }

          // Close modal immediately
          if (onUploaded) onUploaded();
        } else {
          const resp = xhr.responseText;
          console.error("[Upload] Server rejected with", xhr.status, resp);
          try {
            const errObj = JSON.parse(resp);
            // Surface whichever field the backend uses for the error reason
            const msg =
              errObj.message || errObj.error || errObj.detail ||
              errObj.msg || errObj.reason || JSON.stringify(errObj);
            setError(`Upload failed (${xhr.status}): ${msg}`);
          } catch {
            setError(`Upload failed (${xhr.status}): ${resp || xhr.statusText}`);
          }
          setUploading(false);
        }
      };

      xhr.onerror = () => {
        setError("Network error. Please check your connection and try again.");
        setUploading(false);
        addNotification({
          type: "error",
          title: "Upload failed",
          message: "A network error occurred. Please check your connection and try again.",
        });
      };

      xhr.ontimeout = () => {
        setError("Upload timed out. Please try again.");
        setUploading(false);
      };

      xhr.send(formData);
    } catch (err) {
      console.error("Upload Process Error:", err);
      setError(err.message || "An unexpected error occurred during upload.");
      setUploading(false);
    }
  };

  const togglePreviewPlayback = () => {
    if (!previewVideoRef.current) return;

    if (isPlaying) {
      previewVideoRef.current.pause();
    } else {
      previewVideoRef.current.play();
    }
    setIsPlaying(!isPlaying);
  };

  const visibilityIcons = {
    Public: <Globe size={16} />,
    Unlisted: <EyeOff size={16} />,
    Private: <Lock size={16} />
  };

  return (
    <div className="fixed inset-0 bg-black/90 backdrop-blur-md flex items-end sm:items-center justify-center z-[9999] p-0 sm:p-4 animate-in fade-in duration-300">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 100 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        className="bg-[#0f0f0f] border border-white/10 text-white w-full max-w-[900px] min-h-[600px] max-h-[90vh] rounded-t-[32px] sm:rounded-[32px] shadow-2xl overflow-hidden flex flex-col md:flex-row relative"
      >
        {/* Left Side: Preview & Progress */}
        <div className="w-full md:w-[340px] bg-[#0a0000]/40 p-6 border-r border-white/5 hidden md:flex flex-col">
          <div className="flex items-center gap-3 mb-8">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-red-500 to-red-700 flex items-center justify-center shadow-lg shadow-red-500/20">
              <Film size={20} className="text-white" />
            </div>
            <div>
              <h1 className="text-xl font-black tracking-tighter uppercase italic">AirStreamX</h1>
              <p className="text-[10px] text-zinc-500 uppercase tracking-wider">Upload Studio</p>
            </div>
          </div>

          <div className="flex-1 space-y-6">
            {/* Video Preview */}
            <div className="space-y-2">
              <p className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Live Preview</p>
              <div className="aspect-video bg-black rounded-2xl border border-white/5 overflow-hidden flex items-center justify-center relative group shadow-inner">
                {videoPreview ? (
                  <>
                    <video
                      ref={previewVideoRef}
                      src={videoPreview}
                      className="w-full h-full object-cover"
                      loop
                      muted={isMuted}
                      onPlay={() => setIsPlaying(true)}
                      onPause={() => setIsPlaying(false)}
                    />

                    {/* ── FIX: always show selected thumbnail as overlay when not playing ──
                        The HTML poster attribute only works before first play.
                        Using an <img> overlay means the selected frame always shows. */}
                    {!isPlaying && thumbnailPreview && (
                      <img
                        src={thumbnailPreview}
                        alt="Selected thumbnail"
                        className="absolute inset-0 w-full h-full object-cover z-10 pointer-events-none"
                      />
                    )}

                    {/* Hover controls */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center z-20">
                      <button
                        onClick={togglePreviewPlayback}
                        className="p-4 bg-white/20 backdrop-blur-md rounded-full hover:bg-white/30 transition-colors"
                      >
                        {isPlaying ? <Pause size={24} /> : <Play size={24} />}
                      </button>
                    </div>
                    <div className="absolute bottom-2 right-2 flex gap-2 z-20">
                      <button
                        onClick={() => setIsMuted(!isMuted)}
                        className="p-1.5 bg-black/60 backdrop-blur-md rounded-lg opacity-0 group-hover:opacity-100 transition-opacity hover:bg-black/80"
                      >
                        {isMuted ? <VolumeX size={14} /> : <Volume2 size={14} />}
                      </button>
                    </div>
                  </>
                ) : (
                  <div className="text-center">
                    <Film className="text-zinc-800 mx-auto mb-2" size={40} />
                    <p className="text-xs text-zinc-700">No video selected</p>
                  </div>
                )}
              </div>
            </div>

            {/* Video Metadata */}
            {videoMetadata && (
              <div className="bg-[#110000]/30 rounded-xl p-3 space-y-2 text-xs">
                <div className="flex justify-between">
                  <span className="text-zinc-500">Duration</span>
                  <span className="font-mono text-white">{formatDuration(videoMetadata.duration)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-zinc-500">Resolution</span>
                  <span className="font-mono text-white">{videoMetadata.width}×{videoMetadata.height}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-zinc-500">Size</span>
                  <span className="font-mono text-white">{formatBytes(videoMetadata.size)}</span>
                </div>
              </div>
            )}

            {/* Progress Steps */}
            <div className="space-y-3">
              {[
                { id: 1, label: "Upload & Details", icon: UploadCloud },
                { id: 2, label: "Customize", icon: Settings },
                { id: 3, label: "Complete", icon: CheckCircle }
              ].map((s) => (
                <div key={s.id} className="flex items-center gap-3 text-zinc-400 group">
                  <div className={`w-8 h-8 rounded-full border-2 flex items-center justify-center text-xs font-bold transition-all duration-500 ${step >= s.id
                    ? 'border-red-500 text-red-500 bg-red-500/10'
                    : 'border-zinc-700 text-zinc-700'
                    }`}>
                    {step > s.id ? (
                      <CheckCircle size={14} />
                    ) : (
                      <s.icon size={14} />
                    )}
                  </div>
                  <span className={`text-sm font-medium transition-colors ${step === s.id ? 'text-white' : 'text-zinc-500'
                    }`}>
                    {s.label}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Footer Info */}
          <div className="mt-auto p-4 bg-[#110000]/50 rounded-2xl border border-white/5">
            <div className="flex items-center gap-2 text-zinc-400 mb-2">
              <Info size={12} />
              <span className="text-[10px] font-bold uppercase tracking-wider">Guidelines</span>
            </div>
            <p className="text-[10px] text-zinc-500 leading-relaxed">
              By uploading, you agree to our Terms of Service and Community Guidelines. Max file size: 100 MB now.
            </p>
          </div>
        </div>

        {/* Right Side: Form Content */}
        <div className="flex-1 flex flex-col bg-zinc-950 max-h-[90vh] md:max-h-none">
          {/* Header */}
          <div className="px-6 py-5 flex items-center justify-between border-b border-white/5 flex-shrink-0">
            <div>
              <h2 className="text-lg font-bold flex items-center gap-2">
                {step === 1 && <><FileVideo size={20} /> Video Upload</>}
                {step === 2 && <><Sparkles size={20} /> Finalize Publishing</>}
                {step === 3 && <><CheckCircle size={20} /> Ready to Go!</>}
              </h2>
              <p className="text-xs text-zinc-500 mt-0.5">
                {localStorage.getItem("airstream_draft") ? "Draft saved" : "No draft saved"}
              </p>
            </div>
            <div className="flex items-center gap-2" style={{ minHeight: "40px" }}>
              {localStorage.getItem("airstream_draft") && step < 3 && (
                <button
                  onClick={clearDraft}
                  className="p-2 hover:bg-red-500/10 rounded-full transition-colors text-red-500"
                  title="Clear draft"
                >
                  <Trash2 size={16} />
                </button>
              )}
              <button
                onClick={handleClose}
                disabled={uploading}
                className="p-2 hover:bg-white/10 rounded-full transition-colors text-zinc-500 hover:text-white disabled:opacity-20 disabled:cursor-not-allowed"
              >
                <X size={20} />
              </button>
            </div>
          </div>

          {/* Content Area */}
          <div className="flex-1 p-6 md:p-8 overflow-y-auto custom-scrollbar">
            {/* Error Message */}
            <AnimatePresence>
              {error && (
                <motion.div
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -10 }}
                  className="mb-6 p-4 bg-red-500/10 border border-red-500/20 rounded-2xl flex items-start gap-3 text-red-400 text-sm"
                >
                  <AlertCircle size={20} className="flex-shrink-0 mt-0.5" />
                  <div className="flex-1">
                    <p className="font-semibold mb-1">Upload Error</p>
                    <p className="text-xs text-red-300">{error}</p>
                  </div>
                  <button
                    onClick={() => setError("")}
                    className="p-1 hover:bg-red-500/20 rounded transition-colors"
                  >
                    <X size={14} />
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            <AnimatePresence mode="wait">
              {/* STEP 1: File Upload & Basic Info */}
              {step === 1 && (
                <motion.div
                  key="step1"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="space-y-6"
                >
                  {!file ? (
                    <div
                      onDragEnter={handleDrag}
                      onDragOver={handleDrag}
                      onDragLeave={handleDrag}
                      onDrop={handleDrop}
                      className={`relative border-2 border-dashed rounded-[32px] min-h-[320px] flex flex-col items-center justify-center transition-all cursor-pointer group ${isDragging
                        ? 'border-red-500 bg-red-500/10 scale-[0.98]'
                        : 'border-zinc-800 hover:border-zinc-600 bg-[#0a0000]/20 hover:bg-[#0a0000]/40'
                        }`}
                      onClick={() => fileInputRef.current.click()}
                    >
                      <motion.div
                        animate={{ y: isDragging ? -10 : 0 }}
                        className="w-24 h-24 rounded-3xl bg-gradient-to-br from-zinc-800 to-zinc-900 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform shadow-xl"
                      >
                        <UploadCloud
                          size={40}
                          className={`transition-colors ${isDragging ? 'text-red-500 animate-bounce' : 'text-zinc-500 group-hover:text-zinc-400'}`}
                        />
                      </motion.div>
                      <h3 className="text-xl font-bold mb-2">
                        {isDragging ? "Drop your video here" : "Upload your video"}
                      </h3>
                      <p className="text-sm text-zinc-500 mb-1">Drag and drop or click to browse</p>
                      <p className="text-xs text-zinc-600">Maximum file size: 100MB • MP4, MOV, AVI, WebM</p>

                      <div className="mt-8 flex gap-3">
                        <button className="px-8 py-3 bg-gradient-to-r from-red-600 to-red-700 text-white font-bold rounded-full text-sm hover:scale-105 transition-transform active:scale-95 shadow-lg shadow-red-600/30">
                          Select File
                        </button>
                      </div>

                      <input
                        ref={fileInputRef}
                        type="file"
                        accept="video/*"
                        onChange={(e) => processFile(e.target.files[0])}
                        hidden
                      />
                    </div>
                  ) : (
                    <div className="space-y-6">
                      {/* File Info Card */}
                      <div className="bg-[#0a0000]/50 border border-white/5 rounded-2xl p-4 flex items-center gap-4">
                        <div className="w-12 h-12 rounded-xl bg-red-500/10 flex items-center justify-center flex-shrink-0">
                          <Video size={24} className="text-red-500" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-semibold truncate">{file.name}</p>
                          <p className="text-xs text-zinc-500">
                            {formatBytes(file.size)} • {videoMetadata ? formatDuration(videoMetadata.duration) : 'Processing...'}
                          </p>
                        </div>
                        <button
                          onClick={() => {
                            setFile(null);
                            setVideoPreview("");
                            setAutoGeneratedThumbs([]);
                            setThumbnailPreview("");
                            setVideoMetadata(null);
                          }}
                          className="p-2 hover:bg-red-500/10 rounded-lg transition-colors text-red-500"
                        >
                          <Trash2 size={18} />
                        </button>
                      </div>

                      {/* Title Input */}
                      <div className="space-y-2">
                        <label className="text-xs font-black text-zinc-600 uppercase tracking-widest flex items-center gap-2">
                          <Type size={14} /> Video Title *
                        </label>
                        <input
                          className="w-full p-4 bg-[#0a0000] border border-white/5 rounded-2xl focus:ring-2 focus:ring-red-500/30 focus:border-red-500/50 outline-none text-lg font-medium transition-all placeholder:text-zinc-700"
                          placeholder="Add a compelling title..."
                          value={title}
                          onChange={(e) => setTitle(e.target.value)}
                          maxLength={150}
                        />
                        <div className="flex justify-between text-xs">
                          <span className="text-zinc-600">{title.length}/100 characters</span>
                          {titleSuggestions.length > 0 && (
                            <button
                              onClick={generateAISuggestions}
                              className="text-red-500 hover:text-red-500 flex items-center gap-1"
                            >
                              <Sparkles size={12} /> Get AI suggestions
                            </button>
                          )}
                        </div>
                      </div>

                      {/* Description */}
                      <div className="space-y-2">
                        <label className="text-xs font-black text-zinc-600 uppercase tracking-widest flex items-center gap-2">
                          <Settings size={14} /> Description
                        </label>
                        <textarea
                          rows={5}
                          className="w-full p-4 bg-[#0a0000] border border-white/5 rounded-2xl focus:ring-2 focus:ring-red-500/30 focus:border-red-500/50 outline-none text-sm resize-none text-zinc-300 transition-all placeholder:text-zinc-700"
                          placeholder="Tell viewers what your video is about..."
                          value={description}
                          onChange={(e) => setDescription(e.target.value)}
                          maxLength={5000}
                        />
                        <p className="text-xs text-zinc-600 text-right">{description.length}/5000</p>
                      </div>

                      {/* Next Button */}
                      <button
                        disabled={!title.trim()}
                        onClick={() => {
                          setStep(2);
                          generateAISuggestions();
                        }}
                        className="w-full bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 disabled:opacity-30 disabled:cursor-not-allowed py-4 rounded-2xl font-black uppercase tracking-widest text-sm flex items-center justify-center gap-2 transition-all shadow-xl shadow-red-600/20"
                      >
                        Continue to Details <ChevronRight size={18} />
                      </button>
                    </div>
                  )}
                </motion.div>
              )}

              {/* STEP 2: Customization */}
              {step === 2 && (
                <motion.div
                  key="step2"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="space-y-6"
                >
                  {/* Thumbnail Selection */}
                  <div className="space-y-3">
                    <label className="text-xs font-black text-zinc-600 uppercase tracking-widest flex items-center gap-2">
                      <ImagePlus size={14} /> Thumbnail Selection
                    </label>
                    <div className="grid grid-cols-3 gap-3">

                      {/* ── Custom Upload Cell ── */}
                      <label
                        className={`aspect-video rounded-xl relative overflow-hidden cursor-pointer group transition-all duration-200
                          ${thumbnail
                            ? 'border-2 border-red-500 shadow-lg shadow-red-500/20 ring-2 ring-red-500/20'
                            : 'border-2 border-dashed border-zinc-700 hover:border-red-500/60 hover:shadow-lg hover:shadow-red-500/10'
                          }`}
                      >
                        {thumbnail ? (
                          <>
                            <img src={thumbnailPreview} className="w-full h-full object-cover" alt="Custom thumbnail" />
                            <div className="absolute inset-0 bg-black/70 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center gap-1.5">
                              <RotateCcw size={16} className="text-white" />
                              <span className="text-[9px] font-bold text-white uppercase tracking-wider">Change</span>
                            </div>
                            <div className="absolute top-1.5 left-1.5 px-1.5 py-0.5 bg-red-500 rounded text-[8px] font-black text-white uppercase tracking-wider">
                              Custom
                            </div>
                            <button
                              type="button"
                              onClick={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                setThumbnail(null);
                                setThumbnailPreview(autoGeneratedThumbs[3] || "");
                              }}
                              className="absolute top-1 right-1 p-1 bg-black/70 hover:bg-red-500 rounded-full transition-colors opacity-0 group-hover:opacity-100"
                            >
                              <X size={10} className="text-white" />
                            </button>
                          </>
                        ) : (
                          <div className="w-full h-full bg-gradient-to-br from-zinc-900 to-[#0a0000] flex flex-col items-center justify-center gap-1.5 group-hover:from-zinc-800 transition-all duration-200">
                            <div className="w-8 h-8 rounded-full bg-red-600/10 border border-red-500/20 flex items-center justify-center group-hover:bg-red-600/20 group-hover:border-red-500/40 group-hover:scale-110 transition-all duration-200">
                              <ImagePlus size={15} className="text-red-500" />
                            </div>
                            <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest group-hover:text-red-500 transition-colors">Upload</span>
                            <span className="text-[8px] text-zinc-600 group-hover:text-zinc-500 transition-colors">JPG · PNG · WEBP</span>
                          </div>
                        )}
                        <input
                          ref={thumbnailInputRef}
                          type="file"
                          accept="image/jpeg,image/png,image/webp,image/gif"
                          onChange={handleThumbnailChange}
                          hidden
                        />
                      </label>

                      {/* ── Auto-generated frames: skeletons while extracting ── */}
                      {autoGeneratedThumbs.length > 0
                        ? autoGeneratedThumbs.slice(0, 5).map((src, i) => (
                          <button
                            key={i}
                            onClick={() => {
                              setThumbnailPreview(src);
                              setThumbnail(null);
                              // Pause the video so the thumbnail overlay shows immediately
                              if (previewVideoRef.current && !previewVideoRef.current.paused) {
                                previewVideoRef.current.pause();
                                setIsPlaying(false);
                              }
                            }}
                            className={`aspect-video rounded-xl overflow-hidden cursor-pointer border-2 transition-all hover:scale-105 ${thumbnailPreview === src && !thumbnail
                                ? 'border-red-500 shadow-lg shadow-red-500/20 ring-2 ring-red-500/20'
                                : 'border-white/5 hover:border-white/20'
                              }`}
                          >
                            <img src={src} className="w-full h-full object-cover" alt={`Frame ${i + 1}`} />
                          </button>
                        ))
                        : Array.from({ length: 5 }).map((_, i) => (
                          <div key={i} className="aspect-video rounded-xl border border-white/5 bg-zinc-900 relative overflow-hidden">
                            <div className="absolute inset-0 bg-gradient-to-r from-zinc-900 via-zinc-800 to-zinc-900 animate-pulse" />
                            <div className="absolute inset-0 flex items-center justify-center">
                              <Loader2 size={14} className="text-zinc-700 animate-spin" />
                            </div>
                          </div>
                        ))
                      }
                    </div>
                  </div>

                  {/* Category & Visibility */}
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label className="text-xs font-black text-zinc-600 uppercase tracking-widest">Category</label>
                      <select
                        value={category}
                        onChange={(e) => setCategory(e.target.value)}
                        className="w-full p-4 bg-[#0a0000] border border-white/5 rounded-2xl outline-none text-sm font-semibold cursor-pointer hover:bg-[#110000] transition-colors"
                      >
                        {["Entertainment", "Gaming", "Music", "Education", "Tech", "Sports", "Vlog", "Comedy"].map(c => (
                          <option key={c} value={c}>{c}</option>
                        ))}
                      </select>
                    </div>

                    <div className="space-y-2">
                      <label className="text-xs font-black text-zinc-600 uppercase tracking-widest">Visibility</label>
                      <select
                        value={visibility}
                        onChange={(e) => setVisibility(e.target.value)}
                        className="w-full p-4 bg-[#0a0000] border border-white/5 rounded-2xl outline-none text-sm font-semibold cursor-pointer hover:bg-[#110000] transition-colors"
                      >
                        {["Public", "Unlisted", "Private"].map(v => (
                          <option key={v} value={v}>{v}</option>
                        ))}
                      </select>
                    </div>
                  </div>

                  {/* Visibility Info */}
                  <div className="p-3 bg-[#0a0000]/50 rounded-xl border border-white/5 flex items-start gap-3 text-xs">
                    <div className="p-1.5 bg-[#110000] rounded-lg">
                      {visibilityIcons[visibility]}
                    </div>
                    <div>
                      <p className="font-semibold text-white mb-1">{visibility} Video</p>
                      <p className="text-zinc-500 text-xs">
                        {visibility === "Public" && "Anyone can search for and view this video."}
                        {visibility === "Unlisted" && "Only people with the link can view this video."}
                        {visibility === "Private" && "Only you can view this video."}
                      </p>
                    </div>
                  </div>

                  {/* Tags */}
                  <div className="space-y-2">
                    <label className="text-xs font-black text-zinc-600 uppercase tracking-widest flex items-center gap-2">
                      <Tag size={14} /> Search Tags
                    </label>
                    <input
                      className="w-full p-4 bg-[#0a0000] border border-white/5 rounded-2xl outline-none text-sm text-zinc-300 focus:ring-2 focus:ring-red-500/30 transition-all placeholder:text-zinc-700"
                      placeholder="coding, tutorial, javascript (separated by commas)"
                      value={tags}
                      onChange={(e) => setTags(e.target.value)}
                    />

                    {/* Suggested Tags */}
                    {suggestedTags.length > 0 && (
                      <div className="flex flex-wrap gap-2 mt-3">
                        <span className="text-xs text-zinc-500">Suggested:</span>
                        {suggestedTags.map((tag, i) => (
                          <button
                            key={i}
                            onClick={() => addSuggestedTag(tag)}
                            className="px-3 py-1 bg-[#110000] hover:bg-red-600 rounded-full text-xs font-medium transition-colors border border-white/5 hover:border-red-500"
                          >
                            + {tag}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Action Buttons */}
                  <div className="pt-4 flex items-center gap-4">
                    {!uploading ? (
                      <>
                        <button
                          onClick={() => setStep(1)}
                          className="flex-1 px-8 py-4 rounded-2xl font-bold bg-[#0a0000] border border-white/5 hover:bg-[#110000] transition-colors flex items-center justify-center gap-2"
                        >
                          <ChevronLeft size={18} /> Back
                        </button>
                        <button
                          onClick={startUpload}
                          disabled={!title.trim()}
                          className="flex-[2] bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 disabled:opacity-30 py-4 rounded-2xl font-black uppercase tracking-widest text-sm shadow-xl shadow-red-600/30 transition-all hover:-translate-y-0.5 disabled:cursor-not-allowed"
                        >
                          <Zap size={16} className="inline mr-2" />
                          Publish Now
                        </button>
                      </>
                    ) : (
                      <div className="w-full space-y-5">
                        {/* Upload Header */}
                        <div className="flex justify-between items-start">
                          <div className="flex items-center gap-3">
                            <Loader2 className="animate-spin text-red-500" size={28} />
                            <div>
                              <p className="text-base font-black text-white uppercase tracking-tight">{processingStage}</p>
                              <p className="text-xs text-zinc-500 mt-0.5">
                                {uploadSpeed > 0 && `${formatBytes(uploadSpeed)}/s • `}
                                {timeRemaining > 0 && `${Math.floor(timeRemaining / 60)}m ${timeRemaining % 60}s remaining`}
                              </p>
                            </div>
                          </div>
                          <div className="text-right">
                            <span className="text-3xl font-black bg-gradient-to-r from-red-500 to-red-700 bg-clip-text text-transparent tabular-nums">
                              {progress}%
                            </span>
                          </div>
                        </div>

                        {/* Progress Bar */}
                        <div className="w-full h-3 bg-[#0a0000] rounded-full overflow-hidden border border-white/5 p-0.5">
                          <motion.div
                            className="h-full bg-gradient-to-r from-red-600 via-red-500 to-red-600 rounded-full shadow-lg shadow-red-500/50"
                            initial={{ width: 0 }}
                            animate={{ width: `${progress}%` }}
                            transition={{ type: "spring", bounce: 0, duration: 0.4 }}
                          />
                        </div>

                        {/* Upload Stats */}
                        <div className="grid grid-cols-3 gap-3 text-center text-xs">
                          <div className="p-3 bg-[#0a0000]/50 rounded-xl">
                            <p className="text-zinc-500 mb-1">Uploaded</p>
                            <p className="font-bold text-white">{formatBytes(file.size * (progress / 100))}</p>
                          </div>
                          <div className="p-3 bg-[#0a0000]/50 rounded-xl">
                            <p className="text-zinc-500 mb-1">Total Size</p>
                            <p className="font-bold text-white">{formatBytes(file.size)}</p>
                          </div>
                          <div className="p-3 bg-[#0a0000]/50 rounded-xl">
                            <p className="text-zinc-500 mb-1">Speed</p>
                            <p className="font-bold text-white">{formatBytes(uploadSpeed)}/s</p>
                          </div>
                        </div>

                        {/* Cancel Button */}
                        <button
                          onClick={() => {
                            if (confirm("Are you sure you want to cancel this upload?")) {
                              xhrRef.current?.abort();
                              setUploading(false);
                              setProgress(0);
                            }
                          }}
                          className="w-full text-xs uppercase font-bold text-zinc-600 hover:text-red-500 transition-colors tracking-widest py-2"
                        >
                          Cancel Upload
                        </button>
                      </div>
                    )}
                  </div>
                </motion.div>
              )}

              {/* STEP 3: Success */}
              {step === 3 && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="py-12 flex flex-col items-center text-center"
                >
                  <div className="relative mb-8">
                    <motion.div
                      animate={{
                        scale: [1, 1.05, 1],
                        rotate: [0, 5, -5, 0]
                      }}
                      transition={{
                        repeat: Infinity,
                        duration: 3,
                        ease: "easeInOut"
                      }}
                      className="w-28 h-28 bg-gradient-to-br from-green-500/20 to-emerald-500/20 rounded-full flex items-center justify-center relative"
                    >
                      <div className="absolute inset-0 bg-gradient-to-br from-green-500/10 to-emerald-500/10 rounded-full blur-xl"></div>
                      <CheckCircle size={64} className="text-green-500 relative z-10" strokeWidth={2.5} />
                    </motion.div>
                  </div>

                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                  >
                    <h3 className="text-4xl font-black bg-gradient-to-r from-red-500 to-red-700 bg-clip-text text-transparent mb-3 uppercase tracking-tighter">
                      Upload Complete!
                    </h3>
                    <p className="text-zinc-400 mb-4 max-w-[400px] mx-auto leading-relaxed">
                      Your video "{title}" has been uploaded successfully and is now being processed.
                    </p>
                    <p className="text-sm text-zinc-500 mb-10">
                      Processing usually takes a few minutes. You'll be notified when it's live!
                    </p>
                  </motion.div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 w-full max-w-md">
                    <button
                      onClick={onClose}
                      className="px-6 py-4 bg-[#0a0000] border border-white/5 rounded-2xl font-bold hover:bg-[#110000] transition-all hover:scale-105 active:scale-95"
                    >
                      View Dashboard
                    </button>
                    <button
                      onClick={() => {
                        setFile(null);
                        setStep(1);
                        setVideoPreview("");
                        setAutoGeneratedThumbs([]);
                        setThumbnailPreview("");
                        setTitle("");
                        setDescription("");
                        setTags("");
                        setVideoMetadata(null);
                        setProgress(0);
                        setUploadSpeed(0);
                        setTimeRemaining(0);
                      }}
                      className="px-6 py-4 bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 rounded-2xl font-bold transition-all hover:scale-105 active:scale-95 shadow-lg shadow-red-600/30"
                    >
                      Upload Another
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </motion.div>

      <style>{`
        .custom-scrollbar::-webkit-scrollbar { width: 6px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #27272a; border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #3f3f46; }
        
        @keyframes shimmer {
          0% { background-position: -1000px 0; }
          100% { background-position: 1000px 0; }
        }
      `}</style>
    </div>
  );
}